# Generated by Django 5.0.7 on 2024-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='category/icons/')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'web_category',
            },
        ),
    ]
