# Generated by Django 5.0.7 on 2024-07-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ratings', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('created_by', models.CharField(max_length=25)),
                ('languages', models.TextField()),
                ('thumbnail_img', models.ImageField(blank=True, upload_to='courses/thumbnail')),
                ('original_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
            options={
                'verbose_name_plural': 'courses',
                'db_table': 'web_course',
            },
        ),
    ]
