# Generated by Django 5.0.7 on 2024-07-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='original_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='ratings',
            field=models.FloatField(),
        ),
    ]
