# Generated by Django 5.0.7 on 2024-07-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_course_lectures_course_total_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
